version: "3.9"
services:
  postgres:
    image: postgres:15
    container_name: aprendecode_postgres
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: aprendecode_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./api/migrations:/docker-entrypoint-initdb.d

  pgadmin:
    image: dpage/pgadmin4
    container_name: aprendecode_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@local
      PGADMIN_DEFAULT_PASSWORD: pgadmin
    ports:
      - "5050:80"
    depends_on:
      - postgres

  api:
    build: ./api
    container_name: aprendecode_api
    ports:
      - "3000:3000"
    env_file:
      - ./api/.env
    depends_on:
      - postgres
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  postgres_data:
