version: "3.8"

services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: aprendecode_db
    volumes:
      - aprendecode_pgdata:/var/lib/postgresql/data
      - ./api/migrations:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@local
      PGADMIN_DEFAULT_PASSWORD: pgadmin
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  aprendecode_pgdata:
    name: aprendecode_pgdata
